version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
    depends_on:
      - redis

  # Multiple worker instances - each will auto-discover available ports
  worker:
    build: .
    ports:
      - "8080:8080"
    command: python worker.py
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      # All workers have observability enabled, they'll auto-discover ports
      - ENABLE_OBSERVABILITY=true
      - OBSERVABILITY_PORT=8080  # Starting port, will auto-increment if taken
    depends_on:
      - redis
    deploy:
      replicas: 1

volumes:
  redis_data:
