version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: python worker.py
    volumes:
      - .:/app
    depends_on:
      - redis
