[project]
name = "app"
version = "0.1.0"
dependencies = [ 
    "python-dotenv==1.0.0",
    "pydantic", 
    "openai>=2.0.0",
    "redis==6.1.0",
    "fastapi==0.115.12",
    "uvicorn[standard]==0.34.2",
    "websockets==15.0.1",
    "vercel>=0.5.1",
    "vercel-workers",
    "nfactorial==0.1.31",
]
requires-python = "~=3.12.0"

[[tool.uv.sources.nfactorial]]
path = "./wheels/nfactorial-0.1.31-py3-none-any.whl"
